Function sendITMeeting() {
    $dateTitle = (Get-Date -format d)
    $meetingFile = # Location of meeting file generated by PyMeetings

    $outlook = New-Object -ComObject Outlook.Application
    $Mail = $Outlook.CreateItem(0)
    $Mail.To = "" # Insert person you'd like to address here!
    $Mail.Subject = "IT Meeting Attendance " + $dateTitle
    $Mail.Body = "Attached is the meeting attendance sheet. 
    
    
    
    
    
    
    
    
    This message was automatically generated by PowerShell."
    $Mail.Attachments.Add($meetingFile)
    $Mail.Send()

    archiveItem
}

Function archiveItem() {
    $newFileName = "IT_Meeting_" + (Get-Date -format D) + ".txt"
    
    Copy-Item # file locations go here of course
}

sendITMeeting